name: Push CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Build with Gradle
      id: build
      env:
        KEYSTORE_PATH: "../keystore.jks"
        KEYSTORE_PASSWORD: mmm666
        KEY_ALIAS: WearOS
        KEY_PASSWORD: mmm666
      run: |
        echo 'org.gradle.jvmargs=-Xmx3072m' >> gradle.properties
        echo /u3+7QAAAAIAAAABAAAAAQAGd2Vhcm9zAAABjS9QTbsAAAUBMIIE/TAOBgorBgEEASoCEQEBBQAEggTpizRMtzZNCOHHDJKY96d8uKZciLasjP0SYkFl7JIVxyFOQJ38bD6Ir1KEh12/fiCrTI2ZjS8WFHzazhyGEtC/mXkk4YRDeRVYMfJILDPRuBkIQpamGkX60O1tOCgUpvt0hQOhAFyHA1RmwIymSJkdjAvTP42Vof0ruE42NI4Bfsy3TUALc3gp5s08S8nMxwbpfnMrwaqS5NEtNZjiZ5a2O+LFsVSiw9cLLB+nkxYAsItjqZ6jLBp+lia2iAclwiz5/DaKg9ZK7Q/jkxE1rW+Etk82qHhab6u29vFZGliCPfwEuAK9MYG+Lw31LGJSP93F3TYIAIqZse+iDxJO2U5KT1rilP4olU68aNmtodUHbMowHwXA07qPb8qticQvFRnb43eXbm7EEnvuQhpQUL1luUz+swj2/YAtMXFTFqaiVShLvFTYjcT0sCW5DPSbCbWgMOu9K556A8vjqnxsJL0nDCqCAnbARFR0udAZzNcMZFTVrgjh8NR68z5G0JY4V5B8h36kRZYhXpZdLdNqqo75LuwdmonTxshANd9++ddj/6ZQJ7mq1yA9ipmBUhuVMmTUitH7I4VD0SRcvUea0JxX1HklsNQD2fe/qZfzhut8VtPtiZ/SMSSRlbd4XSucwa1BCg7LcZ/OSMqYd9fhE98J/XrFMzML6gI95+ssOnvSJQtGhP7tUDnpfLx22vPP9Jy3Nb+5L3xk23MalDVzIDxH/DkAeyihVbwpd7J8h9+7cg1jkyDp7sPkhkT04+RO3wAPvPWZvP/mEEgB3sX5pPosX3+C2AEt9nc60bvIxUFu5WmZA54kY1Q7d4/Iq1nnay4+cSN9PGZlJAqNfHNoYT/VJfkZJ25Pclsv1BdvEnNGhzoTL997DE6nABUdi80NvSef2uMY/y8CdOUGKlI7sx6EbK8CSa3nC1ag+FSqDUe1/WBw3NH7TFea8BZiQbOpv/stUDctUngY7xuPOFlvATUkhKcMVjXWtVxHtPEB83KOHeVPM+UAEdaJ76h3fiX/F4SZHKLd4KAWSukgVhwAPpVgJlIJqy/2RWDPAhrnThE5ZKihD/1CZ5xbFFqNZAe3I3zv44Lyl1FRV558d7SC+D7EqsZrD12X3cqJb3qZibv09MNEEl3AbP0wIiFDuhXXRxIFxWnT8kkzub9p9n5aYVIFzX457wa3cXaFFduPZsmZR8h5fgA8m+KETpR7vObgmdjNuta9poeml/Q8h1gYicXlyg09c6H02t7+rY0/Ch3S2C9/SVPb67YeQXpolqSO7JuC+UtEJ1jIUQv81LXFmA8sa1A+bSoc8fu+cA2KUoYeShxEvlz3mIARTU8r17DUkLtbqVdostHFYlPOpUJnmp4TUp2mFOnLMBo/xQV7jKVOQbSw3xmBOpOwd5AF2kbrduXEBknVfxQ6RHUUdsXE8Z4uSbmVpvwTBYfGbzdwqBXdPcRAvZuf8yglQJxDNqpETU86OA/uhVZ8b0FThXA6WpkU4Z0vME4zZnJHDaksjOZ1INmstDP0FOxi202iGBNqWtV13ttavVdfyh1KA76pRiTk5v06ayd/zM9wsx4Ed84T/EPLlHsddEddyT6Jc07E8q7MGx85oja9Sy9w7mWuFmjTnsin8OIkIrPTBbOIXy/K0/Yjy8DvSwEpD7KE3YbrKtPJTVBmiFalFsqIAAAAAQAFWC41MDkAAAKcMIICmDCCAYCgAwIBAgIEPO+0sjANBgkqhkiG9w0BAQUFADANMQswCQYDVQQGEwJjbjAgFw0yMzEyMjMwMzU2NDhaGA8yMDg0MDMwNzAzNTY0OFowDTELMAkGA1UEBhMCY24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8pKB9QMUB0/jZwjSxZbi+zpM6yM3uUC9JXTnSxZhd9YOsdOaWwe2cXdEhpKTQlrR6CBw5Ga84LOFgy1VTX4z+QjhePSE2I/8Ln4vNVsNsH9rJODNv+ynnrn2BTaJGPO65y9DO02nw6Fn+tPwqLLc7/ABJCJOsO5GUMfMw8uVpYcKWRjemk+Fr+NPdvpbSD0+rWatDDbJKwxM4kNQzC1aaz8jLZkT+d64TdtA6bKzZotkf4tpcmRjfUs7glt2LdVjLJpv37HurtmI60bsrAe5uJzDgICOEFOiM/RfTFSrlzrHJyv9vDl9EsMlY2QHdNfhuE+WJHZN7pkKtzTTwjdMrAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBACinRtrprDibRGuTD7jSApEDPp8it6Ly4vmU8JJ9iz5ptdFywjcstQcNkpOAoxvr3h+pTa/J1KAgheGZAIlGR8CABvVMglCOynMa99a7b2AXVMHwlYyKqKWg4Og0VhfiyidOl+N26yajT9iZI64cJI2Dli9nwTo9/JkufMKzCMFuG0Pk++hywhPbk3eI9DVFuP6kSC32GEwZ/AAdpTAKrDRVONo+rMJbymAgZeC8btUTcP+PGsfx5FslrZCDLkBfdQTGMoW1obIYQjfNyMz2w5q4yPj6dr8WRvrhUvvy2dPcaZXyMm+jb5IzCux4dz/sxWdwkM2XlUaV8klaz4DbIbapFzr781W+6D83hMBsu8sojReWOw== | base64 -d > keystore.jks
        chmod 777 *
        ./gradlew assembleRelease --stacktrace
        rm keystore.jks
        echo "APkFileName=$(find app/build/outputs/apk/release -name "*.apk")" >> $GITHUB_ENV
        echo "::set-output name=status::success"
 
    - name: Upload Artefact
      uses: actions/upload-artifact@main
      if: steps.build.outputs.status == 'success' && !cancelled()
      with:
        name: app-release
        path: ${{ env.APkFileName }}

      # https://github.com/yujincheng08/BiliRoaming/blob/019eb71afa1887a461f7603987c822ea3fd67f88/.github/workflows/android.yml#L50
    - name: Post to channel
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      env:
        CHANNEL_ID: ${{ secrets.TELEGRAM_TO }}
        BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        FILE: ${{ github.workspace }}/${{ env.APkFileName }}
        COMMIT_MESSAGE: |+
          New push to github\!
          ```
          ${{ github.event.head_commit.message }}
          ```by `${{ github.event.head_commit.author.name }}`
          See commit detail [here](${{ github.event.head_commit.url }})
          Snapshot apk is attached
      run: |
        ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
        curl -v "https://api.telegram.org/bot${{ secrets.BOTTOKEN }}/sendMediaGroup?chat_id=${{ secrets.MESSAGEID }}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://release%22,%22parse_mode%22:%22MarkdownV2%22,%22caption%22:${ESCAPED}%7D%5D"  -F release="@$FILE"
